name: golangci-lint
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.14.4
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.4
      - uses: actions/checkout@v2
      - name: Install dep
        run: |
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
          fi
      - name: Prepare codebase for linter (generates deps, stubs)
        run: make lint-prepare
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.19.1
          only-new-issues: true
